### ISSUE TITLE
Problem on Installing " Migration failed. Check output above "

### ISSUE THREAD

**Issue by reym0n** [fytinnovations/oc-careers#53]
Error is here :

Fytinnovations.Careers
- v1.0.1:  Migration "create_skills_table.php" failed, attempting to rollback

In Connection.php line 669:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'fytinnovations_careers_skills' already exists (SQL: create table `fytinnovations_careers_skills` (`id` int unsigned not null auto_increment primary key, `name` var
  char(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)

In Exception.php line 18:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'fytinnovations_careers_skills' already exists

In PDOStatement.php line 117:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'fytinnovations_careers_skills' already exists

                                                                                                                        
 **[ERROR] Migration failed. Check output above**

**Comment by bojko91** [comment]
Did you try to clear DB ? Just the lines fytinnovations_careers  and try to run migration again?

**Comment by reym0n** [comment]
> Did you try to clear DB ? Just the lines fytinnovations_careers and try to run migration again?

Yes . Solved . Thanks
