### ISSUE TITLE
Carrers Plugin activation issue 

### ISSUE THREAD

**Issue by kgangadhar** [fytinnovations/oc-careers#58]
![xorbit_error3](https://github.com/fytinnovations/oc-careers/assets/6524303/2db1ad0c-3824-4c30-9950-2c9f21c6d781)
![xorbit_error2](https://github.com/fytinnovations/oc-careers/assets/6524303/4931091d-7d18-41ea-9522-b8adf707b6d9)
![xorbit_error1](https://github.com/fytinnovations/oc-careers/assets/6524303/8e477471-e120-4bb1-8c81-52234ce4536b)

Pls check the screenshots 
when we are trying to install the plugin its giving error .. its because of migration issue ...
database was not migrating because of that entire backend crashed .. 
we need to manually goto cpanel then plugins and delete the plugin to access the backend

**Comment by daftspunk** [comment]
A small modification was needed to the Plugin.php file, getNewApplicationsCount method:

```
public static function getNewApplicationsCount()
{
    try {
        return Application::unRead()->count();
    }
    catch (\Exception $ex) {}
}
```
